Style/Documentation:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 60
